language: java
install:
- bash install.sh
script:
- bash test.sh
before_script:
- bash pull.sh
after_success:
- bash push.sh
env:
  global:
    secure: lMJqUaTnzjotUTIK+xRTAd+T9a56hwCGm6FeDith0P+4fL9ERzEAjGBPBbYly4gGTJT2RAEvqC2UyyE2YWVKNnqawBNe6j3VcpsBqVGeAogA4wYXZYMY4tJ88bLSUWZSdDUYEPDhuCppODGAOiEyJjZLnzJm4+UC25vPMVJYSzuk5XrL8btm45SHoOW3YE4S2UzatxdTkpGIOu8QpUCLOLgmim0agvCkc3JCpGkb8z0vhLTcfMSLgmPtpkWYTKxuaIcUvgSCGNqOUQM6ND+x7L7Ca2PrYvJNtGUIX9nc1dgnlXH4zwcbAhm+sqX0d9Mvc6Ng1a/V2R0d1L/uybBaNgiCQq0eIv89IB0erepd74JPF9BGUkx7MDGv8iNp3KRgGZ1ybnJlet6caChcIAGIheMGygvvhxxvfdsBnyh7Ns7BKjSgpb2yStnlYorwutJW7GrH2CKh+RYdSs4TxJ2MQ6piEkMfdAy0V5IT+ZBtk9xWJVs2FUILfHynImITIKE3eEBatw0k1YZS06Vhf+rG066HEbfBq7Lmfxy+yRu5VjS8qIxIo55lnSmMeh02hDt4xNrrwQ9jYPhGK8l5OTQcD3TFdm2sUaUtVCIUnknz6wfSuLKdWveZCiUbDMY2ZiOx+FX3Af8OsmsxSaVqGy3DVitF/gr4ZjMSDib0TryuAJM=
